export const TIMER_TIME = 60;
export const GAME_INFO_1 = '3 Levels';
export const GAME_INFO_2 = '5 Questions Per Level';
export const LEVEL_1_TIMER = 5;
export const LEVEL_1 = 1;
export const LEVEL_2 = 2;
export const LEVEL_3 = 3;
export const STOP_GAME = 'StopGame';
export const GREETINGS = ['Howdy!','Welcome!','Bonjour!',"What's up!"];